### ISSUE TITLE
cesium-native fails to compile in Visual Studio 17.8.0

### ISSUE THREAD

**Issue by TheMostDiligent** [CesiumGS/cesium-native#761]
Compiling cesium-native with the latest MSVC produces a lot of 4996 warnings that are treated as errors and result in compilation failure:

```
AsyncSystem.cpp
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(1141,31): error C2220: the following warning is treated as an error
1>(compiling source file '../../cesium-native-src/CesiumAsync/src/AsyncSystem.cpp')
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(1141,31): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(1141,31): warning C4996:         with
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(1141,31): warning C4996:         [
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(1141,31): warning C4996:             T=wchar_t
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(1141,31): warning C4996:         ]
```

Platform: Windows 10
Visual Studio Version: 17.8.0 (VisualStudio.17.Release/17.8.0+34309.116)
Compiler version: MSVC 19.38.33130.0
Windows SDK version: 10.0.22621.0
Cesium-native version: v0.29.0

**Comment by TheMostDiligent** [comment]
Fixed in [#767](https://github.com/CesiumGS/cesium-native/pull/767)
