### ISSUE TITLE
Consider to use LLVM-style RTTI for close and open class hierarchies 

### ISSUE THREAD

**Issue by baothientran** [CesiumGS/cesium-native#271]
LLVM project currently disables C++ built-in RTTI, so effectively it cannot use `dynamic_cast` at all. However, it does have its own hand-rolled implementation of the feature using standard C++ in case people want to use it. And the implementation is also much more efficient. The detail for how to use the LLVM RTTI is in this link https://llvm.org/docs/HowToSetUpLLVMStyleRTTI.html.

Also, this link has the sneak peak of its RTTI implementation for open class hierarchies, which I think is very simple to implement and blows my mind due to how genius it is:
https://llvm.org/doxygen/ExtensibleRTTI_8h_source.html

I think 3D tiles or gltf extensions can benefit from the extensible RTTI if we don't want to use `std::any`

**Comment by baothientran** [comment]
I think this maybe a solution for replacing gltf extra that we are currently having at the moment. So currently, we are sending a gltf to the unreal engine side and expect the engine to render it. It would be okay for most of the cases if we expect the engine to render the gltf only and maybe some well known KHR extensions. However, sometimes, content has some extra info that needs to be send to the engine to render, for example, `Watermask` that is stored in the `QuantizedMesh`. The extra info currently is stored in the gltf extra and the engine will need to know the format of it to retrieve the info. The major downside of it is that any format change in the extra will be considered to be a breaking change and it will be very annoyed on the client side to keep track of it.

So with the RTTI above, we can create a base class `TileContent` that returns the base gltf which is the geometry of the tile. Any extra info will be stored in the derived class. The engine will need to downcast it to retrieve the info and render it. Normally downcasting is a bad practice, but I think in this case, it's justified for the below reasons: 
- The extra is now embedded in the C++ class now, so anything change in the extra will lead to compilation error on the client. Previously, any format change will be considered to be a runtime error
- The engine will know which content it deals with instead of a generic gltf file. For example, if the engine side wants to render a quantized mesh, it can render the gltf file, then it can retrieve the watermask to render it too. For how to render the `watermask`, the engine can look up the official specs of the quantized mesh to render it correctly. Similar thing to i3dm, b3dm, or CDB since all of them have an extensive official documentation to let the engine know how to render them. Currently, with a generic gltf, it's not very clear what is the `watermask` and how to render it. Is it belong to quantized mesh, a b3dm, or something else? So I think the below approach, those extra infos can be very documented and readable too. @kring do you have any opinions on this?     

```C++
// cesium-native side
class TileContent {
public:
    virtual ~TileContent() = default;

    const CesiumGltf::Model &getModel() const;

     virtual void load(gsl::span<const std::byte> data) = 0;  
}

class QuantizedMesh : public TileContent {
public:
    const WaterMask &getWaterMask() const;

    void load(gsl::span<const std::byte> data) override;  
}

class B3dm : public TileContent {}

class I3dm : public TileContent {} // this may have some more extra info like number of instances, colors, etc

classs TileLikeContent : public TileContent {} // other types other than 3d tiles. e.g I3S, CDB, etc

class Renderer {
public:
     virtual ~Renderer() = default;

     virtual void render(const TileContent &content) = 0;
}

// engine side
class QuantizedMeshRenderer : public Renderer {
public:
     void render(const TileContent &content) {
         const QuantizedMesh &mesh = down_cast<QuantizedMesh>(content);
         // render the gltf and extra water mask here
     }
}

class B3dmRenderer : public Renderer {}

class I3dmRenderer : public Renderer {}
```

**Comment by kring** [comment]
@baothientran I'm sorry but I actually disagree pretty strongly with this. glTF already has a well thought out mechanism for adding capabilities: extensions. Including the very useful distinction between `extensionsUsed` and `extensionsRequired`. We should avoid using extras, yes, for the reasons you've mentioned. But we should replace them with extensions, not a new system. Ideally, those extensions would be official ones published in the Khronos extension registry. But even if cesium-native defines "private" glTF extensions only for use within the library for things like the quantized mesh watermask, that's still much better in my mind than having mechanisms for extensibility (glTF extensions and TileContent-derived classes) with no clear indication of when to use each.

Ok, let me give you a concrete example. In your example, the `QuantizedMesh` content type has a water mask. Cool. Then we move Cesium World Terrain to 3D Tiles and we want to have a water mask there, too. Crap. Ok, let's add it I guess. This is 3D Tiles Next, though, so it's not a b3dm. It's a glTF. How do we extend a glTF? Oh right, with a glTF extension. Ok, so now rendering engines need to support two different water mask rendering paths: one for the `QuantizedMeshRenderer` and one for the `GltfRenderer`. And they're identicaly, except maybe the types are different.

Assuming you're planning to stick to single-inheritance, this whole scheme is very limiting. We can't mix the same water mask capability into multiple types of content. With glTF extensions, we can.

With glTF extensions, we can also support both forward and backward compatibility by - at our discretion - implementing client-requested conversions. For example, there's no official water mask glTF extension today. So we invent a private one for use by cesium-native, `CESIUM_NATIVE_water_mask` or somesuch, and use that to communicate the quantized-mesh water mask to the rendering engine. Then, later, an official water mask extension, `CESIUM_water_mask` shows up in the extension registry and people start using it with 3D Tiles Next. They're a little different, but we can convert between them without much trouble. A client that indicates support for `CESIUM_NATIVE_water_mask` will continue to receive that extension from quantized-mesh tiles, while cesium-native will convert tiles that use `CESIUM_water_mask` to `CESIUM_NATIVE_water_mask` for that client. Conversely, a client that advertises support only for `CESIUM_water_mask` will have quantized-mesh water masks convert to _that_ format. If the client says it supports both, cesium-native won't do any conversions.

We're not _required_ to provide this backward and forward compatibility via extension conversion. But we can where it's valuable, perhaps with a deprecation warning.

I'm fine with using LLVM RTTI, but not for this purpose.

**Comment by baothientran** [comment]
In the example of moving CWT to 3D tiles next, the engine doesn't need to have two different watermask systems for two different rendering paths. It can have a single watermask render system and be shared between two renderers as there is nothing prevents it from doing it. For example, the engine can create its own Watermask struct parameter (for example `UnrealWatermask`) and convert Cesium-Native QuantizedMesh's `Watermask` struct to that parameter, then feed that struct to its own watermask system.  

If in the future, CWT is moved to 3d-tile-next and gltf and have gltf's EXT_watermask, then the engine can convert that extension to its own `UnrealWatermask` again and use the exact same watermask system in the 3D-tile-next renderer. That way, it doesn't break any quantized mesh renderer, but the gltf renderer gets some extra functionality. So the proposed design has a strong backward and forward comatibility

**Comment by baothientran** [comment]
Also the watermask is a pretty simple example. Let say we want to render a CDB format tile and we want to use extension only to communicate with engine. One problem with it is that it takes us nearly a year to have a thorough extension specs which is 3D-tile-next right now to cover the whole CDB metadata along with good documentation. With the proposed design above, a third party can extend Cesium-Native by implementing the `CDBTileContent` class based on the existing CDB document and feed that to the engine. Then, suppose after all the efforts to implement  the CDB, the 3D-tile-next comes out, the third party can just convert 3D-tile-next to CDB render system and quickly have a new system

**Comment by lilleyse** [comment]
I'm not immersed in this enough to have an informed opinion, but I think a component pattern (aka internal extensions) makes more sense than inheritance if we're rallying around `CesiumGltf::Model` being **the** model interface to other engines.

Though I do worry that more complex internal extensions could be impossible to express with JSON schemas. But I don't have any examples right now.

**Comment by baothientran** [comment]
Also for the question about when to use gltf extension and derived class, I think we use extension when it's an official extension (no temporary, it's either from KHR or Cesium official document) and use derived class for anything else. The reason is that official extension will be stable for a long time as it is discussed and debated for months. I wouldn't consider an extension that is published after only one or two weeks of implementations

**Comment by kring** [comment]
> For example, the engine can create its own Watermask struct parameter (for example UnrealWatermask) and convert Cesium-Native QuantizedMesh's Watermask struct to that parameter, then feed that struct to its own watermask system.

Sure, you could do it that way. But why would you? The way I proposed it, the backward and forward compatibility is handled once in cesium-native. In your proposal, each engine has to have its own backward and forward compatibility code. That seems like a big step back to me.

Now of course there could be some (rare) situations where implementing the compatibility in the rendering engine is more efficient. But that's easily handled in my scheme, too. The rendering engine just advises cesium-native it supports _both_ the old and new extension, and then it can implement each however it likes.

> One problem with it is that it takes us nearly a year to have a thorough extension specs which is 3D-tile-next right now to cover the whole CDB metadata along with good documentation. With the proposed design above, a third party can extend Cesium-Native by implementing the CDBTileContent class based on the existing CDB document and feed that to the engine.

This argument makes no sense to me. CDB is complicated, and it's difficult to support all of its features, so we should make each rendering engine deal with that complexity itself. Why?

cesium-native could very well have lower-level CDB-related code, useful to read and write actual CDB files. And a rendering engine is welcome to use that code if it's useful. But 3D Tiles content should be portrayed as glTF, not CDB.

> I'm not immersed in this enough to have an informed opinion, but I think a component pattern (aka internal extensions) makes more sense than inheritance if we're rallying around CesiumGltf::Model being the model interface to other engines.

Exactly. glTF (with extensions as needed) is the scene representation of cesium-native. glTF's mix-in based approach to extension is _much_ more suitable for this task than anything inheritance based.

> Though I do worry that more complex internal extensions could be impossible to express with JSON schemas. But I don't have any examples right now.

We have a mechanism in cesium-native to extend glTF types - whether core or extensions - with custom behavior if needed. I think we should avoid having custom _data_ outside the JSON schemas, but we could if we needed to.

**Comment by baothientran** [comment]
> Sure, you could do it that way. But why would you? The way I proposed it, the backward and forward compatibility is handled once in cesium-native. In your proposal, each engine has to have its own backward and forward compatibility code. That seems like a big step back to me.

No it's not a step back. Or even if it is, I would say it's very minor from the client side. The example illustrates one of the main points that on the engine side, they can have a single render component that can be shared between two rendering paths. They are not forced to create two different water systems for two different content types. Also you says Cesium-Native provides the facility to convert the new extension to the old one in your design. I don't see why we cannot do that in the above change. It can just provide a convert function to convert the new and stable `CESIUM_watermask` extension to the C++ QuantizedMesh's `watermask` interface if people need such conversion. Then, the engine can use the old render system to render the gltf and the watermask like before.
 
> The rendering engine just advises cesium-native it supports both the old and new extension, and then it can implement each however it likes.

But that requires the rendering engine to explicitly know there is a new extension, and in my limited experience, that is not always the case. This is the scenario that I have in mind. Suppose we publish a private `CESIUM_NATIVE_private_watermask` extension in the `gltf primitive extension` slot and put the documents in our repo, so that engines know how to render it. We then convert quantized mesh to gltf as before and use `CESIUM_NATIVE_private_watermask` extension. Everything works fine for a year, then suddenly the private extension is published into the Khronos extension registry after much debate. However, people vote it to be put in the `gltf material extension` slot and change its name to `CESIUM_watermask_EXT`. Normally, engine will look into gltf primitive's extension slot and look for `CESIUM_NATIVE_private_watermask`. If it's there, they will render the water. If it's not, then it can just skip and render the mesh and texture only. It's always there for a year when engines request quantized mesh and watermask. Then suddenly, that extension is not there any more. There is a very good chance that the engine's users, not developers, will be the ones who notice first that there is no water rendered. They informed back to the developers, and turn out Cesium-Native just moves it to the material extension slot with a different name. At that point, the conversion tool will help after the runtime error. In my opinion, any breaking changes should be communicated by the compiler errors or warning at the very first choice. Any break at runtime will be the last resort. In your scheme, I'm not sure how can we achieve that? From my understanding, it seems to communicate the breaking change using runtime error first, which is a breaking deal to me.

> cesium-native could very well have lower-level CDB-related code, useful to read and write actual CDB files. And a rendering engine is welcome to use that code if it's useful. But 3D Tiles content should be portrayed as glTF, not CDB.

The proposed design still promotes glTF as a very first class citizen as it exists in the base class. Cesium-Native can convert CDB into glTF and supports a wide range of engines through the base class. For the engine, that needs a specific CDB data, it will need to downcast the base to CDB concrete type. But that's the choice of that particular engine, and in my opinion, cesium-native shouldn't care about it beside preserving as much data from CDB for the client. There is no custom mesh or scene description in this case beside that extra info of CDB.

> glTF (with extensions as needed) is the scene representation of cesium-native. glTF's mix-in based approach to extension is much more suitable for this task than anything inheritance based.

I'm okay with a published official extensions as they are very stable. I have a mixed feeling about using cesium-native's own custom extensions to communicate it with a downstream engine that we don't have any control. And I'm willing to go with the extension as the main approach here, but the big question that I have is how do we communicate any breaking changes in the extensions, especially the name change or position change (e.g primitive or material extension slot) to the downstream engines, so that the developers will be the one who notice the error first, not their users?

**Comment by baothientran** [comment]
So after some internal discussion with @lilleyse and @IanLilleyT, it looks like on the CesiumJS, there is a change to move everything to gltf and extension too. I guess we can go with it for now and replace all the extras with the extensions. If there are anything not working with it, I guess we can figure something out. At this point, I think my concern is probably not justified.

**Comment by kring** [comment]
> They are not forced to create two different water systems for two different content types.

Unless the types are different, which they probably will be. In which case they'll have to unify them somehow to send them through the common rendering path.

> In your scheme, I'm not sure how can we achieve that? Unless there is a proper way to document deprecated custom extensions which I can't see at the moment, the breaking change during runtime is a breaking deal to me.

Easy. We add a property to `TilesetContentOptions` to indicate which extensions the rendering engine supports. In your scenario, Unreal says it supports `CESIUM_NATIVE_private_watermask`. It doesn't support the new `CESIUM_watermask_EXT`. So from that, cesium-native can:

* Automatically convert `CESIUM_watermask_EXT` to `CESIUM_NATIVE_private_watermask` for forward compatibility.
* Issue a warning that `CESIUM_NATIVE_private_watermask` is deprecated and will be removed in the future, so rendering engines should transition to the new extension.

Meanwhile, a new engine adds support for `CESIUM_watermask_EXT`. It informs cesium-native in `TilesetContentOptions` that it _only_ supports `CESIUM_watermask_EXT`. cesium-native will automatically convert any content that uses `CESIUM_NATIVE_private_watermask` to `CESIUM_watermask_EXT` for this rendering engine for backward compatibility.

The end result is that we can introduce water masks for 3D Tiles in cesium-native and it will "just work" in every rendering engine that already supports it for quantized-mesh without any code changes. In your scheme this would not be true. Even if cesium-native provides an API for doing the transformation between the old and new water mask, the renderer-side code would need to change to call it. And on top of that, new rendering engines aren't burdened with old stuff. Cesium-native takes care of that, complete with the ability to go through a deprecation period for things that will be removed in the future.

> the big question that I have is how do we communicate any breaking changes in the custom extensions

Extensions - especially private ones - are just classes. We can communicate breaking changes with compiler errors and deprecation warnings just as we would anywhere else.

**Comment by baothientran** [comment]
okay that makes sense to me. Then we will go with extensions as the main approach in replacement for extra

**Comment by kring** [comment]
I think there's no action here, but please reopen if you disagree @baothientran.
