### ISSUE TITLE
Documentation build fails with Doxygen 1.13.2

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-native#1086]
It works fine in Doxygen v1.12.0. But with v1.13.2, we get errors like this:

```
F:/cesium/cesium-unreal-samples/Plugins/cesium-unreal/extern/cesium-native/Cesium3DTilesContent/include/Cesium3DTilesContent/ImplicitTilingUtilities.h(427): error : argument 'ellipsoid' of command @param is not found in the argument list of Cesium3 
DTilesContent::ImplicitTilingUtilities::computeBoundingVolume(const Cesium3DTiles::BoundingVolume &rootBoundingVolume, const CesiumGeometry::OctreeTileID &tileID, const CesiumGeospatial::Ellipsoid &ellipsoid CESIUM_DEFAULT_ELLIPSOID) [F:\cesium\ces 
ium-unreal-samples\Plugins\cesium-unreal\extern\cesium-native\build\doc\cesium-native-docs.vcxproj]

F:/cesium/cesium-unreal-samples/Plugins/cesium-unreal/extern/cesium-native/Cesium3DTilesContent/include/Cesium3DTilesContent/ImplicitTilingUtilities.h(427): error : The following parameter of Cesium3DTilesContent::ImplicitTilingUtilities::computeBo 
undingVolume(const Cesium3DTiles::BoundingVolume &rootBoundingVolume, const CesiumGeometry::OctreeTileID &tileID, const CesiumGeospatial::Ellipsoid &ellipsoid CESIUM_DEFAULT_ELLIPSOID) is not documented: [F:\cesium\cesium-unreal-samples\Plugins\ces 
ium-unreal\extern\cesium-native\build\doc\cesium-native-docs.vcxproj]

    parameter 'CESIUM_DEFAULT_ELLIPSOID'
```

This looks like it might be a Doxygen bug, but I'm not sure.

The Mermaid diagrams are also broken when built with this version:

![Image](https://github.com/user-attachments/assets/6b69ddd4-6a35-47d0-88ac-84bb52d3c4cb)

**Comment by kring** [comment]
Fixed by #1097
