### PR TITLE
Silence MSVC deprecation warning (wd4996)

### LINKED ISSUE #761: cesium-native fails to compile in Visual Studio 17.8.0
Compiling cesium-native with the latest MSVC produces a lot of 4996 warnings that are treated as errors and result in compilation failure:

```
AsyncSystem.cpp
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(1141,31): error C2220: the following warning is treated as an error
1>(compiling source file '../../cesium-native-src/CesiumAsync/src/AsyncSystem.cpp')
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(1141,31): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(1141,31): warning C4996:         with
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(1141,31): warning C4996:         [
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(1141,31): warning C4996:             T=wchar_t
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(1141,31): warning C4996:         ]
```

Platform: Windows 10
Visual Studio Version: 17.8.0 (VisualStudio.17.Release/17.8.0+34309.116)
Compiler version: MSVC 19.38.33130.0
Windows SDK version: 10.0.22621.0
Cesium-native version: v0.29.0

### PR DESCRIPTION
**Pull request by TheMostDiligent**
Fix #761

### CODE REVIEW

**Comment by kring** [comment]
Thanks for the PR @TheMostDiligent. Disabling WD4996 would disable all deprecation warnings, though, which is not good. Better to just disable these specific warnings by defining `_SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING`. You seem to have disallowed me to edit the code in this PR, so I'll close it and open a new one instead.

**Comment by TheMostDiligent** [comment]
@kring Sounds good - thanks!
